apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
    spec:
      containers:
      - name: runner
        image: mctsamiktrng01/sampledockerrepo:dockerconn
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: 20.119.59.87
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          value: B5a1c95325e6130551d71cd46b4f66b2
